name: second_brain_app
services:
  second_brain:
    build:
      context: /DATA/AppData/second-brain-app/docker/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: ""
    cpu_shares: 90
    command: []
    container_name: second_brain_app
    deploy:
      resources:
        limits:
          memory: 4096M
    environment:
      - IGNITION_LOCAL_SITES_PATH=/DATA/Projects/Laravel/simple_laravel_app-to_casaos
      - LARAVEL_SAIL=1
      - WWWUSER=werner
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - XDEBUG_MODE=off
    hostname: second_brain_app
    image: sail-8.3/app:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/laravel/laravel-original.svg
    ports:
      - target: 80
        published: "10888"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/second-brain-app/app
        target: /var/www/html
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/laravel/laravel-original.svg
  index: /
  is_uncontrolled: false
  port_map: "10888"
  scheme: http
  store_app_id: second_brain_app
  title:
    custom: Laravel App
