name: my_laravel_app
services:
  laravel_app:
    build:
      context: /DATA/Projects/Laravel/my_laravel_app/docker/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "1000"
    cpu_shares: 90
    command: []
    container_name: my_laravel_app
    deploy:
      resources:
        limits:
          memory: 4096M
    environment:
      - IGNITION_LOCAL_SITES_PATH=/DATA/Projects/Laravel/my_laravel_app
      - LARAVEL_SAIL=1
      - WWWUSER=werner
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - XDEBUG_MODE=off
    hostname: my_laravel_app
    image: sail-8.3/app:latest
    labels:
      icon: https://raw.githubusercontent.com/WernerLuiz92/Laravel_App_-_CasaOS/main/resources/img/my_laravel_app_logo_1.svg
    ports:
      - target: 80
        published: "10888"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Projects/Laravel/my_laravel_app
        target: /var/www/html
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/WernerLuiz92/Laravel_App_-_CasaOS/main/resources/img/my_laravel_app_logo_1.svg
  index: /
  is_uncontrolled: false
  port_map: "10888"
  scheme: http
  store_app_id: my_laravel_app
  title:
    custom: My Laravel App
